const utils = @import("utils.zig");

const opencl_error_mapping: []const [:0]const u8 = &[_][:0]const u8{
    "DeviceNotFound", "CL_DEVICE_NOT_FOUND",
    "DeviceNotAvailable", "CL_DEVICE_NOT_AVAILABLE",
    "CompilerNotAvailable", "CL_COMPILER_NOT_AVAILABLE",
    "MemObjectAllocationFailure", "CL_MEM_OBJECT_ALLOCATION_FAILURE",
    "OutOfResources", "CL_OUT_OF_RESOURCES",
    "OutOfHostMemory", "CL_OUT_OF_HOST_MEMORY",
    "ProfilingInfoNotAvailable", "CL_PROFILING_INFO_NOT_AVAILABLE",
    "MemCopyOverlap", "CL_MEM_COPY_OVERLAP",
    "ImageFormatMismatch", "CL_IMAGE_FORMAT_MISMATCH",
    "ImageFormatNotSupported", "CL_IMAGE_FORMAT_NOT_SUPPORTED",
    "BuildProgramFailure", "CL_BUILD_PROGRAM_FAILURE",
    "MapFailure", "CL_MAP_FAILURE",
    "MisalignedSubBufferOffset", "CL_MISALIGNED_SUB_BUFFER_OFFSET",
    "ExecStatusErrorForEventsInWaitList", "CL_EXEC_STATUS_ERROR_FOR_EVENTS_IN_WAIT_LIST",
    "CompileProgramFailure", "CL_COMPILE_PROGRAM_FAILURE",
    "LinkerNotAvailable", "CL_LINKER_NOT_AVAILABLE",
    "LinkProgramFailure", "CL_LINK_PROGRAM_FAILURE",
    "DevicePartitionFailed", "CL_DEVICE_PARTITION_FAILED",
    "KernelArgInfoNotAvailable", "CL_KERNEL_ARG_INFO_NOT_AVAILABLE",
    "InvalidValue", "CL_INVALID_VALUE",
    "InvalidDeviceType", "CL_INVALID_DEVICE_TYPE",
    "InvalidPlatform", "CL_INVALID_PLATFORM",
    "InvalidDevice", "CL_INVALID_DEVICE",
    "InvalidContext", "CL_INVALID_CONTEXT",
    "InvalidQueueProperties", "CL_INVALID_QUEUE_PROPERTIES",
    "InvalidCommandQueue", "CL_INVALID_COMMAND_QUEUE",
    "InvalidHostPtr", "CL_INVALID_HOST_PTR",
    "InvalidMemObject", "CL_INVALID_MEM_OBJECT",
    "InvalidImageFormatDescriptor", "CL_INVALID_IMAGE_FORMAT_DESCRIPTOR",
    "InvalidImageSize", "CL_INVALID_IMAGE_SIZE",
    "InvalidSampler", "CL_INVALID_SAMPLER",
    "InvalidBinary", "CL_INVALID_BINARY",
    "InvalidBuildOptions", "CL_INVALID_BUILD_OPTIONS",
    "InvalidProgram", "CL_INVALID_PROGRAM",
    "InvalidProgramExecutable", "CL_INVALID_PROGRAM_EXECUTABLE",
    "InvalidKernelName", "CL_INVALID_KERNEL_NAME",
    "InvalidKernelDefinition", "CL_INVALID_KERNEL_DEFINITION",
    "InvalidKernel", "CL_INVALID_KERNEL",
    "InvalidArgIndex", "CL_INVALID_ARG_INDEX",
    "InvalidArgValue", "CL_INVALID_ARG_VALUE",
    "InvalidArgSize", "CL_INVALID_ARG_SIZE",
    "InvalidKernelArgs", "CL_INVALID_KERNEL_ARGS",
    "InvalidWorkDimension", "CL_INVALID_WORK_DIMENSION",
    "InvalidWorkGroupSize", "CL_INVALID_WORK_GROUP_SIZE",
    "InvalidWorkItemSize", "CL_INVALID_WORK_ITEM_SIZE",
    "InvalidGlobalOffset", "CL_INVALID_GLOBAL_OFFSET",
    "InvalidEventWaitList", "CL_INVALID_EVENT_WAIT_LIST",
    "InvalidEvent", "CL_INVALID_EVENT",
    "InvalidOperation", "CL_INVALID_OPERATION",
    "InvalidGlObject", "CL_INVALID_GL_OBJECT",
    "InvalidBufferSize", "CL_INVALID_BUFFER_SIZE",
    "InvalidMipLevel", "CL_INVALID_MIP_LEVEL",
    "InvalidGlobalWorkSize", "CL_INVALID_GLOBAL_WORK_SIZE",
    "InvalidProperty", "CL_INVALID_PROPERTY",
    "InvalidImageDescriptor", "CL_INVALID_IMAGE_DESCRIPTOR",
    "InvalidCompilerOptions", "CL_INVALID_COMPILER_OPTIONS",
    "InvalidLinkerOptions", "CL_INVALID_LINKER_OPTIONS",
    "InvalidDevicePartitionCount", "CL_INVALID_DEVICE_PARTITION_COUNT",
    "InvalidPipeSize", "CL_INVALID_PIPE_SIZE",
    "InvalidDeviceQueue", "CL_INVALID_DEVICE_QUEUE",
    "InvalidSpecId", "CL_INVALID_SPEC_ID",
    "MaxSizeRestrictionExceeded", "CL_MAX_SIZE_RESTRICTION_EXCEEDED"
};

const OpenCLErrorEnum = utils.buildEnum(i32, opencl_error_mapping);

pub const OpenCLError = error {
    DeviceNotFound,
    DeviceNotAvailable,
    CompilerNotAvailable,
    MemObjectAllocationFailure,
    OutOfResources,
    OutOfHostMemory,
    ProfilingInfoNotAvailable,
    MemCopyOverlap,
    ImageFormatMismatch,
    ImageFormatNotSupported,
    BuildProgramFailure,
    MapFailure,
    MisalignedSubBufferOffset,
    ExecStatusErrorForEventsInWaitList,
    CompileProgramFailure,
    LinkerNotAvailable,
    LinkProgramFailure,
    DevicePartitionFailed,
    KernelArgInfoNotAvailable,
    InvalidValue,
    InvalidDeviceType,
    InvalidPlatform,
    InvalidDevice,
    InvalidContext,
    InvalidQueueProperties,
    InvalidCommandQueue,
    InvalidHostPtr,
    InvalidMemObject,
    InvalidImageFormatDescriptor,
    InvalidImageSize,
    InvalidSampler,
    InvalidBinary,
    InvalidBuildOptions,
    InvalidProgram,
    InvalidProgramExecutable,
    InvalidKernelName,
    InvalidKernelDefinition,
    InvalidKernel,
    InvalidArgIndex,
    InvalidArgValue,
    InvalidArgSize,
    InvalidKernelArgs,
    InvalidWorkDimension,
    InvalidWorkGroupSize,
    InvalidWorkItemSize,
    InvalidGlobalOffset,
    InvalidEventWaitList,
    InvalidEvent,
    InvalidOperation,
    InvalidGlObject,
    InvalidBufferSize,
    InvalidMipLevel,
    InvalidGlobalWorkSize,
    InvalidProperty,
    InvalidImageDescriptor,
    InvalidCompilerOptions,
    InvalidLinkerOptions,
    InvalidDevicePartitionCount,
    InvalidPipeSize,
    InvalidDeviceQueue,
    InvalidSpecId,
    MaxSizeRestrictionExceeded,
};

pub fn translateOpenCLError(error_code: i32) OpenCLError {
    const opencl_error_fields = @typeInfo(OpenCLErrorEnum).@"enum".fields;
    inline for (opencl_error_fields) |field| {
        if (@intFromEnum(@field(OpenCLErrorEnum, field.name)) == error_code){
            return @field(OpenCLError, field.name);
        }
    }

    @panic("Unkwon OpenCL error code");
}
